sudo: required
language: node_js
node_js:
   - "v13.9.0"

services:
  - redis-server

cache:
  directories:
    - ~/.npm
    - node_modules

notifications:
  email: false

script:
  - if [[ $TRAVIS_PULL_REQUEST != false ]]; then npx commitlint-travis; fi
  - yarn
  - yarn lint
  - yarn build

deploy:
  - provider: script
    skip_cleanup: true
    script:
      - npx semantic-release
    on:
      branch: master
      node_js: "v13.9.0"
